# Generated by Django 4.0.6 on 2022-08-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCarrer', models.CharField(max_length=50)),
                ('fundationCarrer', models.CharField(max_length=100)),
            ],
        ),
    ]
