# Generated by Django 4.0.6 on 2022-08-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStudent', models.CharField(max_length=40)),
                ('lastNameStudent', models.CharField(max_length=40)),
                ('dniStudent', models.CharField(max_length=10)),
                ('matStudent', models.CharField(choices=[('0', 'Primera'), ('1', 'Segunda'), ('2', 'Tercera')], max_length=1)),
                ('emailStudent', models.EmailField(max_length=100)),
                ('carrerStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
            ],
        ),
    ]
