# Generated by Django 4.0.6 on 2022-08-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['lastNameStudent'], 'verbose_name': 'Alumnado', 'verbose_name_plural': 'Lista de estudiantes'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes'),
        ),
    ]
