# Generated by Django 4.0.6 on 2022-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiante_options_estudiante_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(null=True, upload_to='estudiantes'),
        ),
    ]
